Fixed external RAM being dead slow
Washi1337/Emux pull request #5
Opened 2020-04-17 19:17 UTC by leefogg

Noticed that the emulator grinds to a halt when writing to external RAM when running the demo [Cenotaph](http://www.pouet.net/prod.php?which=59139) after the splash screen. This probably wont be noticeable in most games as they usually aren't doing anything else when accessing external RAM and grind anyway.
Nonetheless, now the sav file is buffered into RAM where it is accessed lightning fast then dumped back to disk when closed, files remain open during.

2020-04-17 22:51 UTC, leefogg commented
This also fixes a bug where the emulator crashes (attempting to access a closed stream) if you attempt to open another ROM while it is saving.

2020-04-18 17:55 UTC, Washi1337 requested changes
To keep the coding style consistent within the project, I added are some comments regarding code style. Next to the comments, can you please configure your editor to use spaces instead of tabs?

2020-04-18 17:55 UTC, Washi1337 commented on Emux.GameBoy/Cartridge/BufferedExternalMemory.cs
> +		private Stream memoryStream, fileStream;
Please prefix private fields with an underscore to conform with the style of the rest of the project (`_memoryStream`, `_fileStream`)

2020-04-18 17:55 UTC, Washi1337 commented on Emux.GameBoy/Cartridge/BufferedExternalMemory.cs
> +		public BufferedExternalMemory(Stream filestream)
Please use camel casing for parameter names

2020-04-18 17:55 UTC, Washi1337 commented on Emux.GameBoy/Cartridge/BufferedExternalMemory.cs
> +			ms?.Flush();
Don't extensively use the null propagation operator when it's multiple lines in a row that depend on the null check.
e.g. 
```csharp
if (ms == null) 
{
   ... 
}
```

2020-04-18 17:55 UTC, Washi1337 commented on Emux.GameBoy/Cartridge/BufferedExternalMemory.cs
> +namespace Emux.GameBoy.Cartridge {
Please start braces on new line to conform with the style of the rest of the project.

2020-04-19 13:47 UTC, leefogg commented
Changes made

2020-04-26 16:57 UTC, Washi1337 commented
Sorry for the late reply. 

Thanks again for taking the time to improve the emulator :)

2020-04-26 16:57 UTC, merged